// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yndcoduxsqjmsvssqudg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InluZGNvZHV4c3FqbXN2c3NxdWRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMTI4NjksImV4cCI6MjA2MTY4ODg2OX0.u0yogU5P_Pr630HrhPuSeQWRu2X_IjvaOkX1Nyt3IG8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);